# Generated by Django 5.1.1 on 2024-09-24 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinfo',
            name='dob',
            field=models.DateField(max_length=40, null=True),
        ),
    ]
