# Generated by Django 5.1.1 on 2024-09-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_basicinfo_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinfo',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
