# Generated by Django 5.0.3 on 2024-09-25 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_basicinfo_email_basicinfo_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicinfo',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='basicinfo',
            name='last_name',
        ),
    ]
