# Generated by Django 5.1.1 on 2024-09-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_degreemodel_fieldofstudymodel_institutenamemodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinfo',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
