# Generated by Django 5.1.1 on 2024-09-27 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_basicinfo_first_name_basicinfo_last_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='institutenamemodel',
            unique_together={('name', 'established_year')},
        ),
    ]
