# Generated by Django 5.1.1 on 2024-10-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_experiencemodel_interestmodel_languagemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='picture',
            field=models.ImageField(null=True, upload_to='media/user_profile'),
        ),
    ]
