# Generated by Django 5.1.1 on 2024-10-01 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_alter_basicinfo_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=50, null=True)),
                ('job_description', models.TextField(null=True)),
                ('job_location', models.CharField(max_length=100, null=True)),
                ('company_name', models.CharField(max_length=50, null=True)),
                ('company_logo', models.ImageField(null=True, upload_to='media/job/company_logo')),
                ('job_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('internship', 'Internship'), ('freelance', 'Freelance'), ('internship', 'Internship')], max_length=100, null=True)),
                ('salary', models.PositiveBigIntegerField(max_length=100, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('application_deadline', models.DateField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
