# Generated by Django 5.1.1 on 2024-10-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_alter_jobmodel_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='salary',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
