# Generated by Django 5.1.1 on 2024-10-01 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_alter_jobmodel_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyNow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=80, null=True)),
                ('applicant_email', models.EmailField(max_length=80, null=True)),
                ('applicant_resume', models.FileField(null=True, upload_to='media/files/resumes')),
                ('applicant_cover_letter', models.TextField(null=True)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.jobmodel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'job')},
            },
        ),
    ]
